name: Print Message

on:
 push:
  branches:
    - 'master' #changed main to master 

jobs:
   print-message:
     runs-on: ubuntu-latest


     steps:
       - name: Print Message
         run: echo "new Push Detected on main branch"